### ISSUE TITLE
raw daki mp3 nedir yaw :)

### ISSUE THREAD

**Issue by ozkanpakdil** [tugbaustundag/MesajlasmaUygulamasi#1]
bende koda bakıyorum bu diyorum neden böle büyük :) sonunda gördüm beyoncesingleladies.mp3 

gerçi kodda da kullanılmış elinize sağlık :+1:

**Comment by tugbaustundag** [comment]
Push Notification da  default ses haricinde istenilen herhangi bir
baska bir müzikde çalınabilir.Örnek için birtane mp3 koydum.Kodlarda
 bununla alakalı açıklama bulunmaktadır..

24 Mart 2015 08:58 tarihinde özkan pakdil notifications@github.com yazdı:
